### ISSUE TITLE
bower registry

### ISSUE THREAD

**Issue by danheberden** [yearofmoo/AngularJS-Scope.SafeApply#3]
You're listed as `angularjs-scope.safeapply-good` in the bower registry because `angularjs-scope.safeapply` has an invalid git url. Would you like me to remove `-good` and update the other one to the right @url? 

https://github.com/bower/bower/issues/120#issuecomment-18253253

**Comment by matsko** [comment]
Yes please :)

**Comment by danheberden** [comment]
Boom done.
